### ISSUE TITLE
FIX K3S metrics problem

### ISSUE THREAD

**Issue by batleforc** [batleforc/WeeboGitOps#43]
https://github.com/k3s-io/k3s/issues/3619

**Comment by batleforc** [comment]
Alert manager keep firing absent for the next job;
kube-scheduler
kube-proxy
kube-controller

**Comment by nicklausbrown** [comment]
How did you fix this and know it was fixed? Specifically the duplicated metrics?

**Comment by batleforc** [comment]
Hi, yes I fixed it following https://picluster.ricsanfre.com/docs/prometheus/#k3s-components-monitoring
I mostly only have one remaining alert firing
![image](https://github.com/batleforc/WeeboGitOps/assets/24699592/ac334302-ed08-4713-84c3-be6c1ba95d20)

**Comment by batleforc** [comment]
ATM, this repo isn't sync with what is my real environment because for the last 6 month I've been working on securing the whole env.

But if needed I can work on providing what I've done
